### ISSUE TITLE
Network error: document is not defined when accessing page behind withAuth()

### ISSUE THREAD

**Issue by AlexanderProd** [borisowsky/next-advanced-starter#12]
When I try to load a page that requires authentication without being authenticated I get the following  `document is not defined` error  in the server console. 

It appears to be because the `document` variable is obviously not available on the server. 

```
Error while running `getDataFromTree` { Error: Network error: document is not defined
    at new ApolloError (/Users/alexanderhoerl/Sites/thecompanyscout.com/node_modules/apollo-client/bundle.umd.js:92:26)
    at /Users/alexanderhoerl/Sites/thecompany/node_modules/apollo-client/bundle.umd.js:1588:34
    at /Users/alexanderhoerl/Sites/thecompany/node_modules/apollo-client/bundle.umd.js:2008:15
    at Set.forEach (<anonymous>)
    at /Users/alexanderhoerl/Sites/thecompany/node_modules/apollo-client/bundle.umd.js:2006:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/Users/alexanderhoerl/Sites/thecompany/node_modules/apollo-client/bundle.umd.js:2004:20)
    at /Users/alexanderhoerl/Sites/thecompany/node_modules/apollo-client/bundle.umd.js:1483:29
  graphQLErrors: [],
  networkError:
   ReferenceError: document is not defined
       at getToken (/Users/alexanderhoerl/Sites/thecompany/.next/server/static/development/pages/_app.js:466:268)
       at getToken (/Users/alexanderhoerl/Sites/thecompany/.next/server/static/development/pages/_app.js:515:23)
       at Object (/Users/alexanderhoerl/Sites/thecompany/.next/server/static/development/pages/_app.js:619:19)
       at /Users/alexanderhoerl/Sites/thecompany/node_modules/apollo-link-context/lib/index.js:11:47,
  message: 'Network error: document is not defined',
  extraInfo: undefined }
```

Technically everything works, the site can't be accessed and an error is shown to the user but the error log in the server is still annoying. 

I tried to fix it by skipping `cookie.parse()` inside of `getToken()` when there's neither a cookie in the header or `document` is undefined but the error still showed up. 

You could just remove the `console.error` inside the `await getDataFromTree()` try catch block but this obviously doesn't solve the underlying issue.

**Comment by borisowsky** [comment]
@AlexanderProd hi, thank you for pay attention to this. For some reason, I don't recieve same error as you, so... can you check out [this branch](https://github.com/borisowsky/nextjs-apollo-ts-starter/tree/feature/composable-with-apollo) (I just slighly changed `apollo.tsx` and how it connected to `_app.tsx`), do you get same error here?

**Comment by AlexanderProd** [comment]
@borisowsky Unfortunately didn't fix it for me, maybe its because my GraphQL server returns an error when an unauthorized client tries to access a query? 

Also does the new version in the branch remove the ability for static site optimization for all pages because the console.log said so?

**Comment by borisowsky** [comment]
@AlexanderProd does your server response with 200 status on errros (GraphQL requires status `200 OK` for everything...)?
And no, you still can use `withApollo` with `_app.tsx` (for all pages), or seperately for each page.

**Comment by AlexanderProd** [comment]
Yeah my server returns 200 for errors too. Really strange that it still happens.

**Comment by borisowsky** [comment]
@AlexanderProd did you fixed it on your own? I'm still trying to get same results :D

**Comment by AlexanderProd** [comment]
No, didn't fix it but I thought its only on my machine and it didn't bother me anymore, but I guess we can keep it open if you're still searching. :D

**Comment by borisowsky** [comment]
Actually, I removed authentication helpers as it's very opinionated, there is a lot of different scenarios where you want to modify it, so I decided to remove this functionality and only provide authentication middlware (we still send athentication token).

Obviously, this doesn't mean I fixed this particular issue by doing it, so for those  who read this: I'd like to receive feedback (reproducable examples can help a lot), especially if you still get this problem.
